mergeSort:
	@echo "Running merge sort"
	marst mergeSort.alg -o prog.c
	gcc prog.c -lalgol -lm -o prog
	./prog

procedureCalls:
	@echo "Running procedure calls"
	marst procedureCalls.alg -o prog.c
	gcc prog.c -lalgol -lm -o prog
	./prog

scope:
	@echo "Running scope"
	marst scope.alg -o prog.c
	gcc prog.c -lalgol -lm -o prog
	./prog

while:
	@echo "Running while"
	marst while.alg -o prog.c
	gcc prog.c -lalgol -lm -o prog
	./prog


